version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoride_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoride_python
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - DB_NAME=ecoride_db
      - FLASK_APP=main.py
      - FLASK_SECRET_KEY=flask_supersecret
      - FLASK_ENV=development
    ports:
      - "5000:5000"
      - "5173:5173"
    volumes:
      - .:/ecoride_container/
    working_dir: /ecoride_container/ecoride_flask
    depends_on:
      - postgres
    command: >
      bash -c "
      npx @tailwindcss/cli -i app/static/css/styles.css -o app/static/css/tw-output.css --watch &
      npm run dev &
      python main.py
      "

volumes:
  db:
  app_static:
