version: '3.9'

services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecoride_admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecoride_db
    volumes:
      - db:/var/lib/postgresql/data
      - ./ecoride_flask/app/db_store/db_init.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoride_python
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_USER=ecoride_admin
      - DB_PORT=5432
      - DB_PASSWORD=secret
      - DB_NAME=ecoride_db
      - FLASK_APP=main.py
      - FLASK_SECRET_KEY=secret
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/ecoride_container/
    working_dir: /ecoride_container/ecoride_flask
    depends_on:
      - postgres
    command: "python main.py"

volumes:
  db:
  app_static:
